### ISSUE TITLE
OK Meeting 03. Juni

### ISSUE THREAD

**Issue by mariafanger** [DINAcon/event#13]
Last exchange: https://github.com/DINAcon/awards/issues/58

## Traktanden
- Budget Besprechung
- Joel Website Betreuung (Rechnung 2200)
- Mercator Sponsoring anfragen? (Francesca)
- Sessions und Awards Promotion!
  - 4 Sessioneingaben bisher
  - 3 Awardeingaben bisher
  - Zeitplan: https://github.com/DINAcon/awards/tree/master/2021#zeitplan
- DINAcon Awards Jury Ideen: https://github.com/DINAcon/awards/issues/57

**Comment by MarkusTiede** [comment]
<blockquote class="twitter-tweet"><p lang="de" dir="ltr">Jetzt Live: der CALL FOR NOMINATIONS für die diesjährigen DINAcon Awards: <a href="https://t.co/FEpiyHkdir">https://t.co/FEpiyHkdir</a><br><br>Auch 2021 zeichnen wir am 29. Oktober Projekte (in 6 Kategorien: <a href="https://t.co/8hdzkqqKiJ">https://t.co/8hdzkqqKiJ</a> für Digitale Nachhaltigkeit, Nutzung offener Daten/Software &amp; Beitrag zur Gemeinschaft aus. <a href="https://t.co/dm20HetzCJ">pic.twitter.com/dm20HetzCJ</a></p>&mdash; DINAcon (@DINAconCH) <a href="https://twitter.com/DINAconCH/status/1399392224513777665?ref_src=twsrc%5Etfw">May 31, 2021</a></blockquote>

**Comment by MarkusTiede** [comment]
Details Location: https://github.com/baloise/open-source/issues/285

**Comment by MarkusTiede** [comment]
# next meeting on 22. June
