### ISSUE TITLE
Session Eingaben

### ISSUE THREAD

**Issue by mariafanger** [DINAcon/event#16]
## guardrails 
15 >> **9 sessions (3 x 3) - fallback (2 x 4 - 1)** 

ToDo bis zum nächsten OK Call: 9 x **thumbs-up** for the ones you prefer

**Comment by mariafanger** [comment]
Compliance in regulierten Industrien mit Open Source (oder braucht es Virenschutz auf Linux?) - https://dinacon.ch/wp-admin/post.php?post=10966&action=edit

**Comment by mariafanger** [comment]
Collabora Online community – smooth migrations and productivity - https://dinacon.ch/wp-admin/post.php?post=10947&action=edit

**Comment by mariafanger** [comment]
Querying and Indexing Smart Contract Data on Ethereum with The Graph - https://dinacon.ch/wp-admin/post.php?post=10945&action=edit

**Comment by mariafanger** [comment]
Behind the Scenes: Brainstorming with the working Group digital sustainability - https://dinacon.ch/wp-admin/post.php?post=10936&action=edit

**Comment by mariafanger** [comment]
Business Modelle mit Open Source - https://dinacon.ch/wp-admin/post.php?post=10930&action=edit

**Comment by mariafanger** [comment]
Cloud native Identity & Access Management for your product - https://dinacon.ch/wp-admin/post.php?post=10915&action=edit

**Comment by mariafanger** [comment]
inosca – Die kantonale Open Source Community - https://dinacon.ch/wp-admin/post.php?post=10899&action=edit

**Comment by mariafanger** [comment]
swissgeol.ch – a technological innovation - https://dinacon.ch/wp-admin/post.php?post=10882&action=edit

**Comment by mariafanger** [comment]
Media needs to be reinvented. (How) can we do it? - https://dinacon.ch/wp-admin/post.php?post=10866&action=edit

**Comment by mariafanger** [comment]
Eine kurze Anleitung zur Nachhaltigkeit im Digitalen - https://dinacon.ch/wp-admin/post.php?post=10852&action=edit

**Comment by mariafanger** [comment]
Die datengetriebene Verwaltung: Daten- und Statistikkompetenz für den Kanton Zürich - https://dinacon.ch/wp-admin/post.php?post=10835&action=edit

**Comment by mariafanger** [comment]
Agil oder nicht agil? Das ist hier die Frage! - https://dinacon.ch/wp-admin/post.php?post=10804&action=edit

**Comment by mariafanger** [comment]
Open Source Robotic Fabrication with COMPAS FAB - https://dinacon.ch/wp-admin/post.php?post=10791&action=edit

**Comment by mariafanger** [comment]
Build Your First Cyber Forensic Application using Python - https://dinacon.ch/wp-admin/post.php?post=10784&action=edit

**Comment by mariafanger** [comment]
Free and Open-Source Educational Software for Generation Z - https://dinacon.ch/wp-admin/post.php?post=10774&action=edit

**Comment by mariafanger** [comment]
Spatial planning goes open* https://dinacon.ch/wp-admin/post.php?post=11000&action=edit

**Comment by mariafanger** [comment]
Wie Open Government Data und OpenStreetMap näher zusammenrücken könnten https://dinacon.ch/wp-admin/post.php?post=11017&action=edit

**Comment by mariafanger** [comment]
Nachhaltige UX Qualität dank FLUX https://dinacon.ch/wp-admin/post.php?post=11019&action=edit

**Comment by tschitschable** [comment]
> Cloud native Identity & Access Management for your product - https://dinacon.ch/wp-admin/post.php?post=10915&action=edit

Habe ihnen gesagt, sie sollen noch mehr auf Open* fokussieren.

**Comment by MarkusTiede** [comment]
Resolving for 2021 - please feel free to re-open / adjust for 2022.
