### ISSUE TITLE
Traktanden Call 5. Juli

### ISSUE THREAD

**Issue by mariafanger** [DINAcon/event#17]
Follow up to : https://github.com/DINAcon/event/issues/14

**Comment by mariafanger** [comment]
###Sessions
- Eingaben besprechen
- Abstimmen
- Lightningtalks?

###Awards
- Nominationen pushen
- Mailing an OSS Firmen

###Keynotes
- Zusagen, Absagen

###Sponsoring
- BEKB
- Mercator
- Hasler

**Comment by MarkusTiede** [comment]
https://www.baloise.com/de/jobs/blog/rund-um-die-baloise/baloise-eines-der-modernsten-ausbildungszentren-der-schweiz.html

**Comment by MarkusTiede** [comment]
## next exchange: 21.07 at 12.30

home-work: 9 votes per person for session - https://github.com/DINAcon/event/issues/16
