### ISSUE TITLE
Discuss Mediensponsoring IT-Business

### ISSUE THREAD

**Issue by mariafanger** [DINAcon/event#18]
Wir schlagen Ihnen folgendes Angebot vor:

Leistung it Business:
- Inserat 1/4 Seite oder 1/2 Seite, 4-farbig (CMYK) > in der Ausgabe 3/21 vom 1. Oktober (Druckunterlagen bis 10. September)
- Redaktioneller themenbezogener Beitrag (5000-7500 Zeichen inkl. Leerschläge bis 10. September)
- Veröffentlichung des Anlasses auf Event-Seite im Magazin und Online
- Aufführung mit Rectangle-Banner (300 x 250 px) auf Medienpartner Slider auf Startseite und Eventsseite
- Aktuelle Ausgabe 3/21 it business zur Abgabe an Besucher mit Bestellformular zum kostenloses Bezug der Ausgabe 4/2021
- Hinweis in den sozialen Medien

Leistung Dinacon:
- Textliche Erwähnung in allen Newslettern
- Auflage it business
- Logo it business auf Panelen und Folien
- Logo/Link auf Website 
- Logo auf Broschüren oder dergleichen, was möglich wäre
[ Respektive je nach virtueller Umsetzung weitere/andere Plattformen ]

**Comment by MarkusTiede** [comment]
Resolving for 2021 - please feel free to re-open / adjust for 2022.
