### ISSUE TITLE
Medienmitteilung Programm und Tickets

### ISSUE THREAD

**Issue by fbgiardina** [DINAcon/event#19]
- Keynote Speaker Julia Reda
Julia Reda, ehem. EU-Abgeordnete und heute Vorstand der Open Knowledge Foundation und Meinungsfreiheits-Expertin bei der Gesellschaft für Freiheitsrechte, berichtet von der Front im Kampf um ein Internet-taugliches Urheberrecht und den Erfolgen der Bug Bounties auf EU Ebene.
- Keynote Speaker Paul-Olivier Dehaye
Intro Satz folgt
- Programm, Sessions
- Tickets, hybrides Konzept

**Comment by MarkusTiede** [comment]
Resolving for 2021 - please feel free to re-open / adjust for 2022.
