### ISSUE TITLE
Traktanden Call 09. August

### ISSUE THREAD

**Issue by mariafanger** [DINAcon/event#21]
# Awards

- mehr Eingaben nötig, sonst müssen wir 2 Kategorien (Learning und Open Data) streichen
- erstes Kickoff Meeting am Mittwoch

# Sponsoring

- Call mit Laura Marsch, eher interessiert an konferenzsponsoring als am Awardssponsoring
- Freie Tickets für IT-Business?

# Programm

- Vorschlag auf PDF, stimmt das für alle 
- Next Step: weitere Infos an Sessionkontaktpersonen
- weitere Session von Schweizer Startup Grundo
https://grundo.io ?
- Mailings und Social Media Teaser

# Ticketing
- wie können wir Freitickets erstellen, brauchen wir dazu Angaben oder nicht?

**Comment by MarkusTiede** [comment]
Resolving for 2021 - please feel free to re-open / adjust for 2022.
