### ISSUE TITLE
Traktanden Call 30. August

### ISSUE THREAD

**Issue by mariafanger** [DINAcon/event#24]
# Programm:

- Stimmen die Zeiten, Kaffeepausen?
- gibt es eine Hacknight?
- neue Session Sohlingen (stattdessen DN auf eine Lunchsession verschieben?)
- 2 Sessions von Cividi und Swissgeol nicht verbinden sondern beide behalten

## Entscheidungen:
- kleine Zeitliche Änderungen im Programm
- Neue Session Sohlingen nur wenn klarer Mehrwert vorhanden
- beide oben erwähnten Sessions finden einzeln statt
- Awards werden auf 50min gekürzt

# Durchführung, Corona:

- Vorschlag: Livestream nur im Plenum, Sessions aufnehmen und im Nachhinein in einem Paket zur Verfügung stellen.
- Covid Zertifikat für Eintritte?
- Ticketcodes für Freieintritte, wie wird das funktionieren?
- Wurden schon Tickets verkauf?
- Finanzen anschauen
- Umfrage an Teilnehmende nach der Konferenz, zB. mit Fragen zu den Awards und der neuen Location
- Bänz reagiert nicht, ich probiere es ein 3. Mal
- Operative Organisation: froh um Hilfe, Maria wird sich mit Francesca koordinieren, Kristelle anfragen?
- Hat jemand eine Raumübersicht der Baloise?

## Entscheidungen:
- Konferenzinhalte sind NICHT hybrid, nur die Plenums-Punkte werden live auf Youtube gestreamt. So ist die Live-Teilnahme attraktiver (bisher erst 2 verkaufte Tickets) und wir sparen uns sehr viel Aufwand. Online Tickets wurden aus dem Katalog genommen
- Ein Covid-Zertifikat wird für alle vorausgesetzt
- Wir müssen im nächsten Monat sehr viel Marketing betreiben
- Finanzen: Rentabilität muss überprüft werden

# Kommunikation:

- it business artikel bis 10. september, auflagen leite ich an francesca weiter.

# Awards:

- Kategorie Open-Learning: wird wieder gestrichen, wir diskutieren stattdessen einen Special Award
- Open-Business wird auch gestrichen
- Open-Data, Open-Community,Open-Government und Open-Newcomer können durchgeführt werden
- Soll es ein Gewinnerbatch geben (momentan noch ohne Label, rein eine grafische Auszeichnung als Logo)
- Gewinner-Projekte der Awards ins OSS Directory einfügen?

**Comment by MarkusTiede** [comment]
Resolving for 2021 - please feel free to re-open / adjust for 2022.
