### ISSUE TITLE
Virtual participation channels

### ISSUE THREAD

**Issue by loleg** [DINAcon/event#26]
As we discussed in #25 for virtual participation there will be access to the livestream and workshops. For interaction with the moderators and other participants, we are looking at multiple options:

Broadcast / teleconference

- Workshops: chat + voice enabled for all in [BigBlueButton](https://bigbluebutton.org/) (BBB)
- Plenum: chat only Q&A (in BBB, social media, forum..) to keep the focus on the livestream

Interactivity / voting / etc

- Live polling: [built into BBB](https://support.bigbluebutton.org/hc/en-us/articles/1500005216661-Use-polling#h_c8d822d9-7c81-45c1-87b3-6ee1efe0cd39), or open source alternatives like [Particify](https://gitlab.com/particify/dev/foss/arsnova) and [Pingo](http://trypingo.com/en/tour/)
- HACKnight: use [Mozilla Hubs](https://hubs.mozilla.com/) or [Workadventu.re](https://workadventu.re/) for extra atmosphere

Social media / forums

- The official hashtag and @-mentions will be monitored
- We had spam issues last year on YouTube and will disable Comments on the livestreams
- We are considering setting up a GitHub Discussion (see [example here](https://github.com/cividi/geohackmin/discussions)), assuming the barrier of setting up a GitHub account is not too high for our community to participate

## Questions

- Is BBB-chat and social media sufficient, or do we need additional forum? If so, is GitHub Discussions a good choice, or should we instead set up a Discourse forum (e.g. https://forum.opendata.ch / https://ask.fedoraproject.org/ ....) or another solution?
- Should we look at setting up a dedicated conference app, or some other way to tie the platforms together? E.g. https://github.com/loomchild/sojourner-web via FOSSDEM
- What are the important hallmarks of virtual participation, how do we want to leave a memorable experience for virtual ticket holders without distracting too much away from the core purpose and within our tight budget?

**Comment by loleg** [comment]
We decided today to focus on BBB and the Social Media hashtags for virtual participation. I have still started a basic set up of the Discussions forum here: https://github.com/DINAcon/event/discussions/28 - we can test it, and @mariafanger will include questions about Community Platforms in the survey. As I mentioned in the call, I would like to make sure we collect the learnings from our partner communities, and try to use a platform which is as inclusive and open as possible going forward.

**Comment by MarkusTiede** [comment]
Resolving for 2021 - please feel free to re-open / adjust for 2022.
