### ISSUE TITLE
Traktanden Call 27. September

### ISSUE THREAD

**Issue by mariafanger** [DINAcon/event#27]
# Organisatorisches

- Schutzkonzept 
- Medienmitteilung - Kontakte SRF; watson, andere Medien?
- Momentaner Stand Tickets?
- Freitickets (sheet)
- Nathalie ist beim Catering dran
- Hacknight bis wann und virtuell? (habe Andrea gefragt, ob das Gebäude weiterhin offen bleibt)

## awards
- Gewinner stehen fest
- Ideen für nachhaltige Awards-Trophies?

# Konferenzdurchführung

Drehbuch: definitiv hybride Konferenzdurchführung (Github? Youtube? Streamings?)
    **Optionen:**
- Keynotes und Plenum live über einen [https://beee.live/parldigi-ki/we98yjsk](https://beee.live/parldigi-ki/we98yjsk) Livestream
- Youtube
- BBB
- Github Livestream (Oleg?)
- Twitter
- Sessions 11 BBB Räumen
- Awards Livestream 

Grundsatzfrage: Passwortgeschützt??
-> online-Ticketing läuft auch noch am Konferenztag

**Comment by MarkusTiede** [comment]
Resolving for 2021 - please feel free to re-open / adjust for 2022.
