### ISSUE TITLE
Traktanden Call 11. Oktober

### ISSUE THREAD

**Issue by mariafanger** [DINAcon/event#30]
# Tickets

- Ticketstand

# Konferenztag

- Drehbuch, Verantwortungen und Bereiche während des Tages
    - Session Livestreaming: Hat jemand noch Eulen, Kameras oder/und Mikrofone (bestenfalls als Kombi)
    - Fragetool während Konferenz
    - Material sonst: Verantwortlichkeiten und still needed
    - Absage Lightningtalks
    - Transport DO Abend

# Organisatorisch

- Übernachtungen
- Meetings coming up der Bereiche
- Staff Briefing → Separat pro Bereich
- Geschenke Speakers -> pro Session oder pro Speaker?

# Awards

- neue Trophäe und Kollaboration mit OpenSourceSeeds

# Kommunikation

- Neue Mobilisierung!
    - Impacthub Kontake und andere für Amir

**Comment by MarkusTiede** [comment]
Resolving for 2021 - please feel free to re-open / adjust for 2022.
