### ISSUE TITLE
DINAcon (Kompakt: halbtags) am Mittwoch den 23.11.2022 im progr.ch

### ISSUE THREAD

**Issue by MarkusTiede** [DINAcon/event#33]
# current idea(s)
 - [Anne-Kristin Höllwarth](https://www.linkedin.com/in/hoellwarth/) is looking for an event to host with their students as a project
 - potential dates: 23.11 or 25.11

# potential location(s)
 
## Welle7 
only available in 2022 on 10. / 14. Oktober and 12. / 14. Dezember 

## [PROGR](https://www.progr.ch)

Raum: Aula
Termin(e):
Mi 23.11.2022: Vormittag
Mi 23.11.2022: Nachmittag
Mi 23.11.2022: Abend
Beschreibung:
- DINAcon (light): https://dinacon.ch
- 150 PAX
- Aufbau: 07.00 Uhr (sofern möglich), Abbau: ab 18.00 Uhr (evtl. Apéro im Lehrerzimmer/Turnhalle, statt oben)
- Event: 09.00 - 16.00 Uhr + Apéro
- Aula + 3-4 zusätzliche Räume für Sessions

**Comment by MarkusTiede** [comment]
## lightweight
- no awards
- no CfP
- 50:50 moderated and community driven / unconference format
 - https://en.wikipedia.org/wiki/Unconference

**Comment by MarkusTiede** [comment]
13.00 Entry
13:30 Welcome
13.45 1. Keynote
14.30 Break
14.45 Session (3 Workshops)
15.30 Break
15.45 2. Keynote
16.30 Closing Session
16.45 Apéro

**Comment by MarkusTiede** [comment]
To do:
Markus:
- Sync Nathalie
- Programm OK informieren schriftlich bis 25.08.
- Team für Speakersuche zusammenstellen
- Fragt Phillip, ob er wieder für die Tickets zuständig ist
- Klärt Budget-Trägerschaft (CH Open / BFH)

Anii:
- Check Location
- Check Catering
- Check Bühnenmaterial (Nathalie)

**Comment by nathaliesinz** [comment]
Fragen Barbara (Kassier)
•	Wann soll die Dinacon stattfinden? 
•	Wann wissen wir, ob Hasler zusagt? 
•	Wann wissen wir, ob Location "on board"?
•	Wann würde die Dinacon NICHT durchgeführt?
•	Wer hat Kontakt zu möglichen Sponsoren?
•	Wie werden die Studierenden von den Hochschulen unterstützt? gibt es da allenfalls auch noch Unterstützungsbeiträge? die FHNW z.B. hat eine Fonds, um solche Vorhaben zu unterstützen. 
•	Wer "führt" die Studierenden? Wie sind die Aufgaben CH_Open / Studierende verteilt? wer hat die Gesamtevent-Verantwortung?

**Comment by nathaliesinz** [comment]
Fragen Barbara (Kassier)
•	Wann soll die Dinacon stattfinden? 
•	Wann wissen wir, ob Hasler zusagt? 
•	Wann wissen wir, ob Location "on board"?
•	Wann würde die Dinacon NICHT durchgeführt?
•	Wer hat Kontakt zu möglichen Sponsoren?
•	Wie werden die Studierenden von den Hochschulen unterstützt? gibt es da allenfalls auch noch Unterstützungsbeiträge? die FHNW z.B. hat eine Fonds, um solche Vorhaben zu unterstützen. 
•	Wer "führt" die Studierenden? Wie sind die Aufgaben CH_Open / Studierende verteilt? wer hat die Gesamtevent-Verantwortung?

**Comment by maemst** [comment]
Vorschläge für Speakers an der DINAcon 2022 oder DINAcon 2023:
- Melissa Di Donato, CEO SUSE, https://www.linkedin.com/in/melissad2/
- Leandro von Werra, Machine Learning Engineer bei Hugging Face https://www.linkedin.com/in/lvwerra/
- Clarisse Schroeder, Civic Tech Sister https://www.linkedin.com/in/clarisseschroeder/
- Marcel Scholze, Open Source Software Services & IT Sourcing bei PwC https://www.linkedin.com/in/marcelscholze/
- Mahalia Stephan, Product Owner Digitalisierung (und Open Source Specialist) bei SBB AG https://www.linkedin.com/in/mahalia-stephan/

**Comment by nathaliesinz** [comment]
Wir ändern den Namen von DINAcon Light zu DINAcon Kompakt

**Comment by nathaliesinz** [comment]
Wir ändern den Namen von DINAcon Light zu DINAcon Kompakt

**Comment by nathaliesinz** [comment]
Lightning-Talk interessiert: Josua Muheim zu Accessability, Christian Heitzmann mal Infos zuschicken?

**Comment by MarkusTiede** [comment]
# Anfrage zum Sponsored-Track

Könntest du uns noch einige Zusatzinformationen zum Event geben, damit wir die Zielgruppe abschätzen können:
- [ ] Werden auch Teilnehmende von Parldigi erwartet?
- [ ] Wäre es möglich, die Teilnehmerliste vom letzten Jahr zu erhalten?

**Comment by mirodietiker** [comment]
Die Weitergabe von Teilnehmerlisten an Sponsoren ohne Einwilligung ist regelmässig ein Thema in der Medienpräsenz von Datenschutz-Aktivisten.

Also wir sind da jeweils konsequent, dass wir keine Teilnehmerliste an Sponsoren geben (ich nehme an, sie meinen dann eine Liste mit E-Mail-Adresse?).

Auch nicht im laufenden Jahr, wenn dieser Anspruch nicht klar vorher vereinbart wurde...
UND vor allem nur dann, wenn die Teilnehmer beim Sign-Up auch eine Einwilligung erteilt haben. Ich meine das nicht so extremistisch, dass es unbedingt eine separate Checkbox sein muss, aber es muss in den Teilnahmebedingungen usw definitiv vermerkt sein.

**Comment by AniiTheViking** [comment]
Link zum SBB / Adfinis Vortrag:
https://www.hashicorp.com/resources/secrets-management-at-swiss-federal-railways-sbb-with-hashicorp-vault

**Comment by tschitschable** [comment]
Sponsoren angefragt:
SUSE, Puzzle, iQual, Seantis, Avintis, Nutanix, iSolution, ungleich, SBB (via Matthias G.)
Zusagen:
- iQual: Beer Hero (700 CHF)
- Seantis: Coffee Break Hero (700 CHF)

Absagen:
- ungleich

**Comment by tschitschable** [comment]
Lightning Talks:
- Seantis
- Puzzle

Angefragt:
- Pelt8

Offen/TBA:
- Miro
- Christian Heitzmann
- OSS Big
- Canopé

**Comment by AniiTheViking** [comment]
#### Studierende:

- Deborah Dauwalder: Projektleitung, 078 631 60 13
- Dan Fuhrimann: Moderation, 078 896 05 26
- Laura Gross: Kommunikation, 079 896 26 33
- Stefan Stadelmann: Technik, 079 853 39 33
- Stephanie Meier: Regie/Logistik, 079 255 76 78

**Comment by deborahdauwalder** [comment]
Koordination/Administration (Deborah)
- [ ] Bewilligungen einholen
- [ ] Geschenke für Referenten
- [ ] zusätzliches Personal
- [ ] Gästemanagement (Namensschilder)

Moderation (Dan)
- [ ] Begrüssung, Überleitung, Abmoderation
- [ ] mögliche Fragen (mit Markus koordinieren)

Kommunikation (Laura)
- [ ] Save the Date Video
- [ ] Final-Call Video
- [ ] Pre-Kom (Posts vorbereiten)
- [ ] Live-Kom (Filmen für Aftermovie, externe studis)
- [ ] After Movie erstellen (externe Studis)

Technik (Stephanie)
- [ ] Bühnenbild
- [ ] Beamer/Leinwand
- [ ] Licht
- [ ] Audio

Logistik (Stefan)
- [ ] Location Besichtigung
- [ ] Anlieferung von Material für Aufbau
- [ ] Besucherlenkung
- [ ] Bestuhlung
- [ ] Raumplanung
- [ ] Abbau
