### ISSUE TITLE
Search "keynotes & speakers"

### ISSUE THREAD

**Issue by MarkusTiede** [DINAcon/event#6]
I'd propose : https://www.linkedin.com/in/mikemilinkovich/

background: won the business awards last year

**Comment by fbgiardina** [comment]
Ingrid Schneider - Datanökonomie Forscherin Universität Hamburg, Informatik / EIT https://www.routledge.com/The-Politics-and-Policies-of-Big-Data-Big-Data-Big-Brother-1st-Edition/Saetnan-Schneider-Green/p/book/9780367432300

**Comment by fbgiardina** [comment]
Evgeny Morozov - https://en.wikipedia.org/wiki/Evgeny_Morozov Da er so links ist ist er hoffentlich nicht so teuer...

**Comment by fbgiardina** [comment]
Paul-Olivier Dehaye - https://hestialabs.org/en/about/ MyData, neu Hestialabs.org. Datenselbstbestimmung, Algos etc.

**Comment by fbgiardina** [comment]
Dasha Ilina - Centre for Technological Pain - Aktionskünstlerin aus Paris https://dashailina.com/

**Comment by fbgiardina** [comment]
Algorithm Accountability Lab - https://de.wikipedia.org/wiki/Katharina_Zweig

**Comment by fbgiardina** [comment]
Max Schrems - Data, Privacy Shield Abkommen etc. https://en.wikipedia.org/wiki/Max_Schrems

**Comment by fbgiardina** [comment]
Longshot: Mariana Mazzucato - Innovation, Neudenken der Wirtschaft, Patente etc. https://en.wikipedia.org/wiki/Mariana_Mazzucato

**Comment by MarkusTiede** [comment]
# Rahmenbedingungen
 - 2 "diverse" Keynotes
   - Vormittag & Nachmittag
   - eine Vor-Ort + eine virtuell / remote

**Comment by MarkusTiede** [comment]
Mark Shuttleworth
 - https://de.wikipedia.org/wiki/Mark_Shuttleworth

**Comment by MarkusTiede** [comment]
Anna Wohlfarth
 - https://www.stiftung-nv.de/de/person/anna-wohlfarth

**Comment by MarkusTiede** [comment]
Julia Reda
 - https://de.wikipedia.org/wiki/Julia_Reda

**Comment by MarkusTiede** [comment]
Marcin Jakubowski, Ph.D.
 - [Open Source Blueprints for Civilization. Build Yourself.](https://www.opensourceecology.org)

**Comment by MarkusTiede** [comment]
Resolving for 2021 - please feel free to re-open / adjust for 2022.
